# Generated by Django 5.0.3 on 2024-03-28 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this stored filter object', max_length=200, verbose_name='name')),
                ('app_name', models.CharField(max_length=20, verbose_name='app')),
                ('model_name', models.CharField(max_length=20, verbose_name='model')),
                ('data', models.TextField(verbose_name='data')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='last used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_used',),
            },
        ),
    ]
