# Generated by Django 5.0.3 on 2024-04-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_filters_stoex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterstore',
            options={'ordering': ('-stick_to', '-last_used')},
        ),
        migrations.AddField(
            model_name='filterstore',
            name='all_users',
            field=models.BooleanField(default=False, help_text="If this search should appear in every user's list of saved searches", verbose_name='all users'),
        ),
        migrations.AddField(
            model_name='filterstore',
            name='stick_to',
            field=models.IntegerField(choices=[(0, 'Neither'), (1, 'Top'), (-1, 'Bottom')], default=0, help_text='Whether to stick to the top or bottom, or none', verbose_name='stick to'),
        ),
    ]
